import {  Search, Plus, Bell } from "lucide-react";

import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <SidebarProvider>
          <AppSidebar />
          <main className=" w-full">
            <header className="flex h-[64px] items-center justify-between px-8 py-3 border-b border-[#E2E8F0] text-black">
              <SidebarTrigger className="-ml-1" />


              <div className="flex items-center gap-4">
                <div className=" border border-[Slate/200] flex items-center bg-white text-black rounded-md px-3 py-1 w-64">
                  <Search size={16} className="mr-2 text-gray-500" />
                  <input
                    type="text"
                    placeholder="Search"
                    className="bg-transparent flex-grow outline-none text-sm"
                  />
                  <span className="text-xs text-gray-500 ml-2">⌘ K</span>
                </div>

                <button className="p-2 rounded-md bg-green-800 hover:bg-green-900">
                  <Plus size={18} className="text-white" />
                </button>

                <Bell size={20} className="text-gray-300 cursor-pointer" />


                <img
                  src="https://i.pravatar.cc/32"
                  alt="User"
                  className="w-8 h-8 rounded-full"
                />
              </div>
            </header>
            <div className="p-8">
              {children}

            </div>
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
